// <auto-generated />
using System;
using ImportCostPro.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Database.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ISOCode")
                        .IsUnique();

                    b.ToTable("Countries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Countries_ISOCode_Length", "LEN([ISOCode]) >= 2 AND LEN([ISOCode]) <= 3");
                        });
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocalCurrency")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ISOCode")
                        .IsUnique();

                    b.HasIndex("IsLocalCurrency")
                        .IsUnique()
                        .HasFilter("[IsLocalCurrency] = 1");

                    b.ToTable("Currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currencies_ISOCode_Length", "LEN([ISOCode]) >= 3 AND LEN([ISOCode]) <= 3");
                        });
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("SourceCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceCurrencyId");

                    b.HasIndex("TargetCurrencyId");

                    b.ToTable("ExchangeRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExchangeRate_Value_Positive", "RateValue > 0");
                        });
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ImporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransportMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ImporterId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("ImportOrders", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CustomDutyPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DesiredProfitMargin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ImportOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCostFob")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ImportOrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("ImportOrderDetails", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrderExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApportionmentMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<Guid>("ImportOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ImportOrderId");

                    b.ToTable("ImportOrderExpenses", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Importer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Importers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Importers_CountryId_NotEmpty", "[CountryId] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.LandedCostCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CifTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomsServiceFeePercentageUsed")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CustomsServiceFeeTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DutyTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FobTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FobTotalOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FreightTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GeneralItbisPercentageUsed")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ImportOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ImportTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocalCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LocalExpensesTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SelectiveTaxTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ImportOrderId")
                        .IsUnique();

                    b.HasIndex("LocalCurrencyId");

                    b.ToTable("LandedCostCalculations", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.LandedCostCalculationDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CifLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomsServiceFeeCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DesiredProfitMargin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DutyCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExciseTaxPercentageUsed")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FobLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FobOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FreightAssigned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceAssigned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItbisCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LandedCostCalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LocalExpensesAssigned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SelectiveTaxCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SuggestedSellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TariffPercentageUsed")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnitLandedCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LandedCostCalculationId");

                    b.HasIndex("ProductId");

                    b.ToTable("LandedCostCalculationDetails", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TariffCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodeReference")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.HasIndex("TariffCategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.TariffCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ApplyExciseTax")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyITBIS")
                        .HasColumnType("bit");

                    b.Property<decimal>("ExciseTaxPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TariffCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TariffPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TariffCode")
                        .IsUnique();

                    b.ToTable("TariffCategories", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.TaxConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CustomsServiceFeePercentage")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("GeneralItbisPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxConfigurations", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ExchangeRate", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Currency", "SourceCurrency")
                        .WithMany()
                        .HasForeignKey("SourceCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Currency", "TargetCurrency")
                        .WithMany()
                        .HasForeignKey("TargetCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCurrency");

                    b.Navigation("TargetCurrency");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrder", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Importer", "Importer")
                        .WithMany()
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Importer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrderDetail", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.ImportOrder", "ImportOrder")
                        .WithMany("Details")
                        .HasForeignKey("ImportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrderExpense", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.ImportOrder", "ImportOrder")
                        .WithMany("Expenses")
                        .HasForeignKey("ImportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ImportOrder");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Importer", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.LandedCostCalculation", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.ImportOrder", "ImportOrder")
                        .WithMany()
                        .HasForeignKey("ImportOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Currency", "LocalCurrency")
                        .WithMany()
                        .HasForeignKey("LocalCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportOrder");

                    b.Navigation("LocalCurrency");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.LandedCostCalculationDetail", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.LandedCostCalculation", "Calculation")
                        .WithMany("Details")
                        .HasForeignKey("LandedCostCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calculation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Product", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.TariffCategory", "TariffCategory")
                        .WithMany()
                        .HasForeignKey("TariffCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("TariffCategory");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.Supplier", b =>
                {
                    b.HasOne("ImportCostPro.Database.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Database.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.ImportOrder", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("ImportCostPro.Database.Entities.LandedCostCalculation", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
